-- Spring Session JDBC 저장소 스키마.
-- 세션을 JVM 메모리가 아닌 RDS에 저장해, ECS 태스크가 교체돼도 로그인 세션이 유지되게 한다.
-- 컬럼/인덱스 구조는 Spring Session JDBC 표준 스키마를 따른다(JdbcIndexedSessionRepository).
-- MySQL·H2(MODE=MySQL) 공통 실행을 위해 ENGINE=InnoDB / ROW_FORMAT 같은 MySQL 전용 절은 쓰지 않는다
-- (현대 MySQL 기본 엔진이 InnoDB라 불필요). 운영은 이 마이그레이션이, 테스트 H2는 라이브러리
-- embedded 초기화가 테이블을 만든다 — prod는 spring.session.jdbc.initialize-schema=never.

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            CHAR(36)    NOT NULL,
    SESSION_ID            CHAR(36)    NOT NULL,
    CREATION_TIME         BIGINT      NOT NULL,
    LAST_ACCESS_TIME      BIGINT      NOT NULL,
    MAX_INACTIVE_INTERVAL INT         NOT NULL,
    EXPIRY_TIME           BIGINT      NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BLOB         NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);
